### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/lib#80]
Please publish this library on PyPI.

I utilized it as dependency for a [Robot Framework listener](https://gitlab.com/uhbs/robotframework-listener-icinga) and would like to publish the listener but I'm missing this dependency.

```
 py -m twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading robotframework_listener_icinga-0.0.6-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 kB • 00:00 • ?
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Invalid value for requires_dist. Error: Can't have direct dependency: 'lib @ git+https://github.com/slalomsk8er/lib.git@v0.0.1'
```

I can recommend the talk [Publishing (Perfect) Python Packages on PyPi](https://www.youtube.com/watch?v=GIF3LaRqgXo) and the tool recommended at the end `py -m cookiecutter gh:ionelmc/cookiecutter-pylibrary` as it got me started.

**Comment by markuslf** [comment]
https://pypi.org/project/linuxfabrik-lib/

I did this the usual way with setuptools, but `pip install` and the use of the libraries after that still need to be tested.

**Comment by markuslf** [comment]
Yes, we are waiting for our organization to be approved on PyPI.

**Comment by markuslf** [comment]
Since the approval of organizations is paused on pypi.org, I have updated & reactivated the libs on pypi.org.

**Comment by slalomsk8er** [comment]
Worked for https://pypi.org/project/robotframework-listener-icinga/ thanks!
