### ISSUE TITLE
url.lib: Make use of Proxy Environment Variables

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lib#81]
Would be nice to read the details from ENV:
* http_proxy
* https_proxy
* plus authentication

```
# echo $http_proxy
http://user:pass@proxy-host.example.com:port/
```

**Comment by mrimann** [comment]
@markuslf Any chance to get this implemented "soon"? Would a sponsoring speed things up? (if so, just contact me)

**Comment by markuslf** [comment]
Actually, they are used. If you are running Icinga under a system account, you will need to make some configuration changes to pass them to the monitoring plugins. We've tested it all and described it [here](https://github.com/Linuxfabrik/monitoring-plugins?tab=readme-ov-file#tips--tricks).

**Comment by markuslf** [comment]
BTW, as part of our testing, we have also documented relevant parts of a Squid configuration on [docs.linuxfabrik.ch](https://docs.linuxfabrik.ch/software/squid.html).
